services:
  vuejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./MainMakerFront:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
