version: '3.8'

services:
  vite_app:
    build: .
    container_name: vite_vue_app
    ports:
      - "8000:8000"
    volumes:
      # [EXPLICATION: Remplacer <chemin_local_projet> par le chemin absolu vers votre dossier de projet sur votre machine]
      - ./:/app
      # Volume pour les node_modules
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0